imports:
    - resource: parameters.yml
    - resource: security.yml
    - resource: services.yml
parameters:
    locale: en
framework:
    secret: "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: null
    form: null
    csrf_protection: null
    validation:
        enable_annotations: true
    serializer:
        enabled: true
    templating:
        engines:
            - twig
    default_locale: "%locale%"
    trusted_hosts: null
    trusted_proxies: null
    session:
        handler_id: session.handler.native_file
        save_path: "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments: null
    http_method_override: true
    assets: null
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"
doctrine:
    dbal:
        driver: pdo_mysql
        host: "%database_host%"
        port: "%database_port%"
        dbname: "%database_name%"
        user: "%database_user%"
        password: "%database_password%"
        charset: UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
swiftmailer:
    transport: "%mailer_transport%"
    host: "%mailer_host%"
    username: "%mailer_user%"
    password: "%mailer_password%"
    spool:
        type: memory
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
        formats:
            json: true
            xml: true
    format_listener:
        rules:
            - path: ^/
              priorities:
                  - json
                  - xml
              fallback_format: json
              prefer_extension: false
    body_listener:
        enabled: true
    param_fetcher_listener:
        enabled: true
