places:
    type:     rest
    resource: AppBundle\Controller\PlaceController

preferences:
    type:     rest
    resource: AppBundle\Controller\User\PreferenceController

prices:
    type:     rest
    resource: AppBundle\Controller\Place\PriceController

themes:
    type:     rest
    resource: AppBundle\Controller\Place\ThemeController

users:
    type:     rest
    resource: AppBundle\Controller\UserController