AppBundle\Entity\Preference:
    exclusion_policy: none
    properties:
        id:
            groups: ["user", "preference"]
        name:
            groups: ["user", "preference"]
        value:
            groups: ["user", "preference"]
        user:
            groups: ["preference"]
